### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError

### ISSUE THREAD

**Issue by ateliershen** [TypistTech/image-optimize-command#15]
Hi,

Thank you for your package! However, I've encountered an `Uncaught TypeError` during running the command. Could you please take a look? Thank you!

```
PHP Warning:  Use of undefined constant CUSTOM_USER_TABLE - assumed 'CUSTOM_USER_TABLE' (this will throw an Error in a future version of PHP) in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1138) : eval()'d code on line 84
PHP Warning:  Use of undefined constant CUSTOM_USER_META_TABLE - assumed 'CUSTOM_USER_META_TABLE' (this will throw an Error in a future version of PHP) in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1138) : eval()'d code on line 85
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to TypistTech\ImageOptimizeCommand\AttachmentRepository::take() must be of the type integer, string given, called in /root/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/ImageOptimizeCommand.php on line 30 and defined in /root/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/AttachmentRepository.php:20
Stack trace:
#0 /root/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/ImageOptimizeCommand.php(30): TypistTech\ImageOptimizeCommand\AttachmentRepository::take('10')
#1 [internal function]: TypistTech\ImageOptimizeCommand\ImageOptimizeCommand->run(Array, Array)
#2 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(89): call_user_func(Array, Array, Array)
#3 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#4 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(425): call_user_func(Object(Closure), Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(35 in /root/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/AttachmentRepository.php on line 20
Fatal error: Uncaught TypeError: Argument 1 passed to TypistTech\ImageOptimizeCommand\AttachmentRepository::take() must be of the type integer, string given, called in /root/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/ImageOptimizeCommand.php on line 30 and defined in /root/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/AttachmentRepository.php:20
Stack trace:
#0 /root/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/ImageOptimizeCommand.php(30): TypistTech\ImageOptimizeCommand\AttachmentRepository::take('10')
#1 [internal function]: TypistTech\ImageOptimizeCommand\ImageOptimizeCommand->run(Array, Array)
#2 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(89): call_user_func(Array, Array, Array)
#3 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#4 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(425): call_user_func(Object(Closure), Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(35 in /root/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/AttachmentRepository.php on line 20
```

My PHP version is 7.2.4 & WP CLI version is 1.5.1

**Comment by TangRufus** [comment]
Thanks for reporting!

Bug confirmed when invoking via command line:
```bash
$ wp image-optimize run --limit=10
$ wp image-optimize run --limit='10'
```

Or, directly via PHP code:
```php
ImageOptimizeCommand::run(null, [
    'limit' => '10', // string!
);
```
