### ISSUE TITLE
Uncaught Error: Call to undefined method fromShellCommandline()

### ISSUE THREAD

**Issue by ElectroMyStyle** [TypistTech/image-optimize-command#473]
Hi, I wanted to test your image optimization script, but I ran into a problem.
My server is running on Debian 11.
PHP Ver.: 7.4
I have installed WP Cli.
I also installed all the necessary packages:
```
$ sudo apt-get install jpegoptim
$ sudo apt-get install optipng
$ sudo apt-get install pngquant
$ sudo apt-get install gifsicle
```
When testing from the console with the command `wp --allow-root image-optimize batch --limit=10` I get an error:

```
root@1110759-ce36154:/usr/local/lsws/SchoolTop/html# wp --allow-root image-optimize batch --limit=10
===> Backing up full sized images for 1 attachment(s)
===> Backing up 1 full sized image(s)
Success: Backed up full sized image - /usr/local/lsws/SchoolTop/html/wp-content/uploads/2022/11/2-2.jpg
Finished
===> Optimizing images for 1 attachment(s)
===> Optimizing images of attachment ID: 11
===> Optimizing 10 file(s)
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Process\Process::fromShellCommandline() in /root/.wp-cli/packages/vendor/spatie/image-optimizer/src/OptimizerChain.php:97
Stack trace:
#0 /root/.wp-cli/packages/vendor/spatie/image-optimizer/src/OptimizerChain.php(77): Spatie\ImageOptimizer\OptimizerChain->applyOptimizer()
#1 /root/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/Operations/Optimize.php(71): Spatie\ImageOptimizer\OptimizerChain->optimize()
#2 [internal function]: TypistTech\ImageOptimizeCommand\Operations\Optimize->TypistTech\ImageOptimizeCommand\Operations\{closure}()
#3 /root/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/Operations/Optimize.php(69): array_map()
#4 /root/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/Operations/AttachmentImages/Optimize.php(101): TypistTech\ImageOptimizeCommand\Operations\Optimize->execute()
#5 /root/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/Operations/AttachmentImages/Optimize.php(64):  in /root/.wp-cli/packages/vendor/spatie/image-optimizer/src/OptimizerChain.php on line 97
Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Process\Process::fromShellCommandline() in /root/.wp-cli/packages/vendor/spatie/image-optimizer/src/OptimizerChain.php:97
Stack trace:
#0 /root/.wp-cli/packages/vendor/spatie/image-optimizer/src/OptimizerChain.php(77): Spatie\ImageOptimizer\OptimizerChain->applyOptimizer()
#1 /root/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/Operations/Optimize.php(71): Spatie\ImageOptimizer\OptimizerChain->optimize()
#2 [internal function]: TypistTech\ImageOptimizeCommand\Operations\Optimize->TypistTech\ImageOptimizeCommand\Operations\{closure}()
#3 /root/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/Operations/Optimize.php(69): array_map()
#4 /root/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/Operations/AttachmentImages/Optimize.php(101): TypistTech\ImageOptimizeCommand\Operations\Optimize->execute()
#5 /root/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/Operations/AttachmentImages/Optimize.php(64):  in /root/.wp-cli/packages/vendor/spatie/image-optimizer/src/OptimizerChain.php on line 97
Error: A critical error has occurred on the site.Learn more about solving problems with WordPress. A critical error has occurred on the site.
```

The backup file was successfully created, but then, alas, the optimization failed
![image](https://user-images.githubusercontent.com/5159210/203532419-89db5d00-bae3-4b75-b130-e59ba91f453a.png)

Do you have any ideas how to solve this problem?

**Comment by tangrufus** [comment]
Install wp-cli via composer instead of using the phar.
See: https://github.com/TypistTech/image-optimize-command#requirements
